"""
Core module for the Turing Project application.

This module contains the foundational components including:
- Configuration management
- Logging setup
- Base classes and abstractions
- Constants and enums
- Standardized response models
- Custom exception handling
"""

from .config import settings
from .logging import setup_logging, get_module_logger
from .base import BaseService, BaseAPIClient, BaseDataProcessor, BaseSyncService, ServiceResult
from .constants import (
    API_VERSION,
    API_PREFIX,
    HTTP_OK,
    HTTP_CREATED,
    HTTP_BAD_REQUEST,
    HTTP_UNAUTHORIZED,
    HTTP_FORBIDDEN,
    HTTP_NOT_FOUND,
    HTTP_INTERNAL_SERVER_ERROR,
    COLLECTION_USER_SETTINGS,
    COLLECTION_AUDIT_LOGS,
    COLLECTION_SYNC_STATUS,
    JWT_ALGORITHM,
    JWT_EXPIRY_HOURS,
    DEFAULT_SYNC_INTERVAL_MINUTES,
    CANVAS_API_VERSION,
    CANVAS_DEFAULT_PAGE_SIZE,
    CANVAS_MAX_PAGE_SIZE,
    NOTION_API_VERSION,
    NOTION_DEFAULT_PAGE_SIZE,
    NOTION_MAX_PAGE_SIZE,
    FIREBASE_KEYS_DIR,
    SERVICE_ACCOUNT_FILE,
    LOG_DIR,
    ENV_DEVELOPMENT,
    ENV_PRODUCTION,
    ENV_TESTING,
    DEFAULT_LOG_LEVEL,
    DEFAULT_LOG_ROTATION,
    DEFAULT_LOG_RETENTION,
    ERROR_FIREBASE_NOT_AVAILABLE,
    ERROR_INVALID_TOKEN,
    ERROR_UNAUTHORIZED,
    ERROR_NOT_FOUND,
    ERROR_VALIDATION_FAILED,
    ERROR_EXTERNAL_SERVICE,
    SUCCESS_OPERATION,
    SUCCESS_SYNC,
    SUCCESS_AUTH,
    AUDIT_ACTION_LOGIN,
    AUDIT_ACTION_LOGOUT,
    AUDIT_ACTION_SYNC,
    AUDIT_ACTION_UPDATE,
    AUDIT_ACTION_DELETE,
    SyncStatus,
)
from .responses import (
    BaseResponse,
    SuccessResponse,
    ErrorResponse,
    PaginatedResponse,
    HealthCheckResponse,
    SyncStatusResponse,
    success_response,
    error_response,
    paginated_response,
)
from .exceptions import (
    TuringException,
    ValidationError,
    AuthenticationError,
    AuthorizationError,
    DatabaseError,
    ExternalServiceError,
    ConfigurationError,
)

__all__ = [
    # Configuration
    "settings",
    # Logging
    "setup_logging",
    "get_module_logger",
    # Base classes
    "BaseService",
    "BaseAPIClient",
    "BaseDataProcessor",
    "BaseSyncService",
    "ServiceResult",
    # Constants
    "API_VERSION",
    "API_PREFIX",
    "HTTP_OK",
    "HTTP_CREATED",
    "HTTP_BAD_REQUEST",
    "HTTP_UNAUTHORIZED",
    "HTTP_FORBIDDEN",
    "HTTP_NOT_FOUND",
    "HTTP_INTERNAL_SERVER_ERROR",
    "COLLECTION_USER_SETTINGS",
    "COLLECTION_AUDIT_LOGS",
    "COLLECTION_SYNC_STATUS",
    "JWT_ALGORITHM",
    "JWT_EXPIRY_HOURS",
    "DEFAULT_SYNC_INTERVAL_MINUTES",
    "CANVAS_API_VERSION",
    "CANVAS_DEFAULT_PAGE_SIZE",
    "CANVAS_MAX_PAGE_SIZE",
    "NOTION_API_VERSION",
    "NOTION_DEFAULT_PAGE_SIZE",
    "NOTION_MAX_PAGE_SIZE",
    "FIREBASE_KEYS_DIR",
    "SERVICE_ACCOUNT_FILE",
    "LOG_DIR",
    "ENV_DEVELOPMENT",
    "ENV_PRODUCTION",
    "ENV_TESTING",
    "DEFAULT_LOG_LEVEL",
    "DEFAULT_LOG_ROTATION",
    "DEFAULT_LOG_RETENTION",
    "ERROR_FIREBASE_NOT_AVAILABLE",
    "ERROR_INVALID_TOKEN",
    "ERROR_UNAUTHORIZED",
    "ERROR_NOT_FOUND",
    "ERROR_VALIDATION_FAILED",
    "ERROR_EXTERNAL_SERVICE",
    "SUCCESS_OPERATION",
    "SUCCESS_SYNC",
    "SUCCESS_AUTH",
    "AUDIT_ACTION_LOGIN",
    "AUDIT_ACTION_LOGOUT",
    "AUDIT_ACTION_SYNC",
    "AUDIT_ACTION_UPDATE",
    "AUDIT_ACTION_DELETE",
    "SyncStatus",
    # Response models
    "BaseResponse",
    "SuccessResponse",
    "ErrorResponse",
    "PaginatedResponse",
    "HealthCheckResponse",
    "SyncStatusResponse",
    "success_response",
    "error_response",
    "paginated_response",
    # Exceptions
    "TuringException",
    "ValidationError",
    "AuthenticationError",
    "AuthorizationError",
    "DatabaseError",
    "ExternalServiceError",
    "ConfigurationError",
]
